### ISSUE TITLE
Custom entries in auto.master

### ISSUE THREAD

**Issue by damacus** [sous-chefs/autofs#2]
IT was previously possible to add an attribute to a wrapper cookbook as below

default[:autofs][:auto_master_entries] = [
'/home /opt/.wiu/awesome_perl_script.pl nfsvers=3 --timeout=600'
]

This would create an entry in /etc/auto.master that told autofs to call off to a custom perl script.

**Comment by MattMencel** [comment]
Awesome.... thanks!

**Comment by damacus** [comment]
No problem, if you can figure out how to add the functionality feel free to
 add it and some tests.

I shall hopefully get to it soon.

**Comment by damacus** [comment]
Closed by #3
