### ISSUE TITLE
line version requirement is out of date

### ISSUE THREAD

**Issue by in4mer** [sous-chefs/autofs#20]
Hi,

Does this thing really need line ~> 0.6?  1.0.3 is out, I'd like to not depend on old versions if able.

**Comment by richardlock** [comment]
Hi Ian,

Thanks.  There's no requirement to use the old version of the line cookbook, it's just historical.  I'm testing after making the change so will upload a new version asap.

Kind regards, Richard

**Comment by in4mer** [comment]
Awesome, tyvm!
